### ISSUE TITLE
Unfortunately, HTTPS proxy is also not available on iOS (at least, in XCode 16.2)

### ISSUE THREAD

**Issue by smikes** [tailscale/tailscale#15801]
Working to build the new `libtailscale` and TailscaleKit for iOS, I hit:

```
libtailscale/swift/TailscaleKit/URLSession+Tailscale.swift:28:13: error: 'kCFNetworkProxiesHTTPSEnable' is unavailable in iOS
            kCFNetworkProxiesHTTPSEnable: true,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
CFNetwork.kCFNetworkProxiesHTTPSEnable:2:12: note: 'kCFNetworkProxiesHTTPSEnable' has been explicitly marked unavailable here
public let kCFNetworkProxiesHTTPSEnable: CFString
           ^
```

This change was introduced in d5a3c8e8ef4dd04298093a1038d5f44b7658bcf0, to make this work on iOS -- the removed code read in part

```
-    // (barnstar) TODO: kCFNetworkProxiesSOCKS* is not available on iOS
-    //                   is there another way to make this work on non desktops?
-
-    #if os(macOS)
```
